# Generated by Django 4.1.7 on 2023-04-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_products_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='phone_number',
        ),
    ]
