# Generated by Django 4.1.7 on 2023-04-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_postal_code_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv_code',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='validity',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
